[project]
name = "com.MasterPoint"
version = "0.9.5"
dependencies = ["flet>=0.24.1", "requests"]

[tool.flet.android]
permissions = [
    "android.permission.INTERNET",
    "android.permission.READ_EXTERNAL_STORAGE",
    "android.permission.WRITE_EXTERNAL_STORAGE"
]
