[project]
name = "MasterPoint"
version = "1.0.0"
dependencies = ["flet==0.27.6", "flet-geolocator", "requests"]

[tool.flet]
compile.cleanup = true
permissions = ["location"]

[tool.flet.android]
min_sdk_version = 21
target_sdk_version = 34